/**
 * Phase 2 — Validation tests based on exploration JSON output.
 *
 * These tests are PURE: no browser, no network. They read JSON files
 * generated by Phase 1 (npm run explore) and assert on the results.
 *
 * Run:  npm run test:validate
 * Or:   npx playwright test --project=unit-tests tests/iana-validation.spec.ts
 */
import { expect, test } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import type { SerializedGraph, Transition } from '../explorer/types';

const EXPLORATION_DIR = path.resolve(__dirname, '..', '.exploration-data');

type ExplorationOutput = {
  url: string;
  scope: string;
  config: Record<string, unknown>;
  graph: SerializedGraph;
  summary: {
    statesDiscovered: number;
    transitions: number;
    maxDepthReached: number;
    cycles: number;
    deadEnds: number;
    totalDuration: number;
    failedActions: number;
  };
  actions: { type: string; targetUid?: string; priority: number }[];
  scenarios: unknown[];
  mermaid: string;
  dot: string;
  generatedAt: string;
};

function loadExploration(scope: string): ExplorationOutput {
  const filePath = path.join(EXPLORATION_DIR, `iana-${scope}.json`);
  if (!fs.existsSync(filePath)) {
    throw new Error(
      `Exploration JSON not found: ${filePath}\nRun "npm run explore" first to generate exploration data.`
    );
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as ExplorationOutput;
}

function getRootState(data: ExplorationOutput) {
  const roots = data.graph.states.filter((s) => !data.graph.transitions.some((t) => t.to === s.id));
  expect(roots).toHaveLength(1);
  return roots[0];
}

function getNavigationTransitions(data: ExplorationOutput): Transition[] {
  return data.graph.transitions.filter((t) => t.navigationUrl);
}

function getSamePageTransitions(data: ExplorationOutput): Transition[] {
  return data.graph.transitions.filter((t) => !t.navigationUrl);
}

// ============================================================
// Body scope
// ============================================================
test.describe('IANA Validation — body scope', () => {
  let data: ExplorationOutput;

  test.beforeAll(() => {
    data = loadExploration('body');
  });

  test('has a single root state with facts', () => {
    const root = getRootState(data);
    expect(root.facts.length).toBeGreaterThan(0);
    expect(root.depth).toBe(0);
  });

  test('detects at least 20 links', () => {
    const root = getRootState(data);
    const links = root.facts.filter((f) => f.tag === 'a');
    expect(links.length).toBeGreaterThanOrEqual(20);
  });

  test('page is static — no buttons, inputs, selects', () => {
    const root = getRootState(data);
    const nonLinkInteractive = root.facts.filter((f) => f.tag === 'button' || f.tag === 'input' || f.tag === 'select');
    expect(nonLinkInteractive).toHaveLength(0);
  });

  test('RFC 2606 and RFC 6761 links are present', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => f.accessibleName ?? f.text ?? '').join(' ');
    expect(allText).toContain('2606');
    expect(allText).toContain('6761');
  });

  test('all actions are clicks', () => {
    const nonClickActions = data.actions.filter((a) => a.type !== 'click');
    expect(nonClickActions).toHaveLength(0);
  });

  test('actions are sorted by priority descending', () => {
    for (let i = 1; i < data.actions.length; i++) {
      expect(data.actions[i].priority).toBeLessThanOrEqual(data.actions[i - 1].priority);
    }
  });

  test('transitions have navigationUrl', () => {
    const navTransitions = getNavigationTransitions(data);
    expect(navTransitions.length).toBeGreaterThanOrEqual(1);
    for (const t of navTransitions) {
      expect(t.navigationUrl).toMatch(/^https?:\/\//);
    }
  });
});

// ============================================================
// Main scope
// ============================================================
test.describe('IANA Validation — main scope', () => {
  let data: ExplorationOutput;

  test.beforeAll(() => {
    data = loadExploration('main');
  });

  test('has a single root state', () => {
    getRootState(data);
  });

  test('RFC links detected', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).toContain('2606');
    expect(allText).toContain('6761');
  });

  test('no header or footer links in scope', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).not.toContain('protocols');
    expect(allText).not.toContain('privacy policy');
  });

  test('has at least 2 links', () => {
    const root = getRootState(data);
    expect(root.facts.filter((f) => f.tag === 'a').length).toBeGreaterThanOrEqual(2);
  });

  test('all 3 RFC/reserved links navigate externally', () => {
    const navTransitions = getNavigationTransitions(data);
    expect(navTransitions.length).toBeGreaterThanOrEqual(1);
    const urls = navTransitions.map((t) => t.navigationUrl!);
    // At least one RFC link detected
    expect(urls.some((u) => u.includes('rfc') || u.includes('reserved'))).toBe(true);
  });
});

// ============================================================
// Header scope
// ============================================================
test.describe('IANA Validation — header scope', () => {
  let data: ExplorationOutput;

  test.beforeAll(() => {
    data = loadExploration('header');
  });

  test('has a single root state', () => {
    getRootState(data);
  });

  test('does not contain footer or content links', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).not.toContain('privacy policy');
    expect(allText).not.toContain('terms of service');
    expect(allText).not.toContain('rfc 2606');
    expect(allText).not.toContain('rfc 6761');
  });

  test('reasonable number of states', () => {
    expect(data.graph.states.length).toBeLessThanOrEqual(10);
    expect(data.summary.statesDiscovered).toBe(data.graph.states.length);
  });
});

// ============================================================
// Footer scope
// ============================================================
test.describe('IANA Validation — footer scope', () => {
  let data: ExplorationOutput;

  test.beforeAll(() => {
    data = loadExploration('footer');
  });

  test('has a single root state', () => {
    getRootState(data);
  });

  test('contains privacy/terms links', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).toMatch(/privacy|terms/);
  });

  test('does not contain main content links', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).not.toContain('rfc 2606');
    expect(allText).not.toContain('rfc 6761');
  });
});

// ============================================================
// Body content (#body) scope
// ============================================================
test.describe('IANA Validation — body-content scope', () => {
  let data: ExplorationOutput;

  test.beforeAll(() => {
    data = loadExploration('body-content');
  });

  test('has a single root state', () => {
    getRootState(data);
  });

  test('contains RFC links', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).toContain('2606');
    expect(allText).toContain('6761');
  });

  test('has at least 2 links', () => {
    const root = getRootState(data);
    expect(root.facts.filter((f) => f.tag === 'a').length).toBeGreaterThanOrEqual(2);
  });

  test('does not contain footer links', () => {
    const root = getRootState(data);
    const allText = root.facts.map((f) => (f.accessibleName ?? f.text ?? '').toLowerCase()).join(' ');
    expect(allText).not.toContain('privacy policy');
  });
});

// ============================================================
// Cross-scope structural assertions
// ============================================================
test.describe('IANA Validation — structural', () => {
  test('export formats are valid', () => {
    const data = loadExploration('main');

    // Mermaid
    expect(data.mermaid).toMatch(/stateDiagram|graph/);

    // DOT
    expect(data.dot).toContain('digraph {');
    expect(data.dot.trimEnd()).toMatch(/}$/);

    // JSON round-trip
    const roundTripped = JSON.parse(JSON.stringify(data.graph)) as SerializedGraph;
    expect(roundTripped.states).toBeDefined();
    expect(roundTripped.transitions).toBeDefined();
  });

  test('idempotence — main and body-content share root facts', () => {
    const main = loadExploration('main');
    const bodyContent = loadExploration('body-content');

    // Both should detect RFC links
    const mainRoot = getRootState(main);
    const bcRoot = getRootState(bodyContent);
    const mainRfcLinks = mainRoot.facts.filter((f) => (f.text ?? '').includes('RFC'));
    const bcRfcLinks = bcRoot.facts.filter((f) => (f.text ?? '').includes('RFC'));
    expect(mainRfcLinks).toHaveLength(bcRfcLinks.length);
  });

  test('scopes are disjoint — header vs footer', () => {
    const header = loadExploration('header');
    const footer = loadExploration('footer');

    const headerUids = new Set(getRootState(header).facts.map((f) => f.uid));
    const footerUids = new Set(getRootState(footer).facts.map((f) => f.uid));

    // uid is index-based (a[0], a[1]...) so they may collide on index
    // but text content should be different
    const headerTexts = new Set(getRootState(header).facts.map((f) => f.text));
    const footerTexts = new Set(getRootState(footer).facts.map((f) => f.text));
    const overlap = [...headerTexts].filter((t) => footerTexts.has(t));
    // Very few overlaps expected (maybe "About" appears in both)
    expect(overlap.length).toBeLessThan(3);
  });

  test('navigation URLs are real HTTP(S)', () => {
    const data = loadExploration('body');
    const navTransitions = getNavigationTransitions(data);
    for (const t of navTransitions) {
      const url = new URL(t.navigationUrl!);
      expect(['http:', 'https:']).toContain(url.protocol);
    }
  });
});
